"""add publisher_platforms to campaign

Revision ID: 0d33eef01e0e
Revises: 9ba103e4afd8
Create Date: 2026-05-27 14:00:37.511672

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0d33eef01e0e'
down_revision: Union[str, None] = '9ba103e4afd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('publisher_platforms', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('campaigns', sa.Column('instagram_positions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'instagram_positions')
    op.drop_column('campaigns', 'publisher_platforms')
    # ### end Alembic commands ###
