"""Add WhatsApp module tables

Revision ID: 51a54c2fe475
Revises: a3f1c8d92e74
Create Date: 2026-06-01 11:15:54.419563

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '51a54c2fe475'
down_revision: Union[str, None] = 'a3f1c8d92e74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_contacts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('country_code', sa.String(length=10), nullable=False),
    sa.Column('mobile_number', sa.String(length=20), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_contacts_id'), 'whatsapp_contacts', ['id'], unique=False)
    op.create_index(op.f('ix_whatsapp_contacts_mobile_number'), 'whatsapp_contacts', ['mobile_number'], unique=False)
    op.create_index(op.f('ix_whatsapp_contacts_user_id'), 'whatsapp_contacts', ['user_id'], unique=False)
    op.create_table('whatsapp_templates',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('template_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('header_type', sa.String(length=20), nullable=True),
    sa.Column('header_content', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('footer', sa.Text(), nullable=True),
    sa.Column('buttons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_templates_id'), 'whatsapp_templates', ['id'], unique=False)
    op.create_index(op.f('ix_whatsapp_templates_user_id'), 'whatsapp_templates', ['user_id'], unique=False)
    op.create_table('whatsapp_campaigns',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('campaign_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('campaign_type', sa.String(length=50), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['whatsapp_templates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_campaigns_id'), 'whatsapp_campaigns', ['id'], unique=False)
    op.create_index(op.f('ix_whatsapp_campaigns_user_id'), 'whatsapp_campaigns', ['user_id'], unique=False)
    op.create_table('whatsapp_campaign_contacts',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('message_status', sa.String(length=32), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['whatsapp_campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['whatsapp_contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_campaign_contacts_campaign_id'), 'whatsapp_campaign_contacts', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_campaign_contacts_id'), 'whatsapp_campaign_contacts', ['id'], unique=False)
    op.create_table('whatsapp_message_logs',
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['whatsapp_campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['whatsapp_contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['whatsapp_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_message_logs_campaign_id'), 'whatsapp_message_logs', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_message_logs_contact_id'), 'whatsapp_message_logs', ['contact_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_message_logs_id'), 'whatsapp_message_logs', ['id'], unique=False)
    op.drop_index('ix_leads_facebook_page_id', table_name='leads')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_leads_facebook_page_id', 'leads', ['facebook_page_id'], unique=False)
    op.drop_index(op.f('ix_whatsapp_message_logs_id'), table_name='whatsapp_message_logs')
    op.drop_index(op.f('ix_whatsapp_message_logs_contact_id'), table_name='whatsapp_message_logs')
    op.drop_index(op.f('ix_whatsapp_message_logs_campaign_id'), table_name='whatsapp_message_logs')
    op.drop_table('whatsapp_message_logs')
    op.drop_index(op.f('ix_whatsapp_campaign_contacts_id'), table_name='whatsapp_campaign_contacts')
    op.drop_index(op.f('ix_whatsapp_campaign_contacts_campaign_id'), table_name='whatsapp_campaign_contacts')
    op.drop_table('whatsapp_campaign_contacts')
    op.drop_index(op.f('ix_whatsapp_campaigns_user_id'), table_name='whatsapp_campaigns')
    op.drop_index(op.f('ix_whatsapp_campaigns_id'), table_name='whatsapp_campaigns')
    op.drop_table('whatsapp_campaigns')
    op.drop_index(op.f('ix_whatsapp_templates_user_id'), table_name='whatsapp_templates')
    op.drop_index(op.f('ix_whatsapp_templates_id'), table_name='whatsapp_templates')
    op.drop_table('whatsapp_templates')
    op.drop_index(op.f('ix_whatsapp_contacts_user_id'), table_name='whatsapp_contacts')
    op.drop_index(op.f('ix_whatsapp_contacts_mobile_number'), table_name='whatsapp_contacts')
    op.drop_index(op.f('ix_whatsapp_contacts_id'), table_name='whatsapp_contacts')
    op.drop_table('whatsapp_contacts')
    # ### end Alembic commands ###
