"""add facebook_positions

Revision ID: 6e2b633c2952
Revises: 0d33eef01e0e
Create Date: 2026-05-27 14:20:27.526576

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '6e2b633c2952'
down_revision: Union[str, None] = '0d33eef01e0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('facebook_positions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'facebook_positions')
    # ### end Alembic commands ###
