"""Add Instagram support

Revision ID: 9ba103e4afd8
Revises: 002
Create Date: 2026-05-27 13:04:23.424587

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9ba103e4afd8'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instagram_accounts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('facebook_page_id', sa.UUID(), nullable=False),
    sa.Column('instagram_account_id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('profile_picture', sa.String(length=1024), nullable=True),
    sa.Column('access_token', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['facebook_page_id'], ['facebook_pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instagram_accounts_facebook_page_id'), 'instagram_accounts', ['facebook_page_id'], unique=False)
    op.create_index(op.f('ix_instagram_accounts_id'), 'instagram_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_instagram_accounts_instagram_account_id'), 'instagram_accounts', ['instagram_account_id'], unique=True)
    op.create_index(op.f('ix_instagram_accounts_user_id'), 'instagram_accounts', ['user_id'], unique=False)
    op.create_index(op.f('ix_ad_accounts_facebook_account_id'), 'ad_accounts', ['facebook_account_id'], unique=False)
    op.create_index(op.f('ix_ads_adset_id'), 'ads', ['adset_id'], unique=False)
    op.create_index(op.f('ix_ads_user_id'), 'ads', ['user_id'], unique=False)
    op.create_index(op.f('ix_adsets_campaign_id'), 'adsets', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_adsets_user_id'), 'adsets', ['user_id'], unique=False)
    op.add_column('campaigns', sa.Column('platform', sa.String(length=32), server_default='facebook', nullable=False))
    op.create_index(op.f('ix_campaigns_ad_account_id'), 'campaigns', ['ad_account_id'], unique=False)
    op.create_index(op.f('ix_facebook_pages_facebook_account_id'), 'facebook_pages', ['facebook_account_id'], unique=False)
    op.create_index(op.f('ix_forms_page_id'), 'forms', ['page_id'], unique=False)
    op.create_index(op.f('ix_forms_user_id'), 'forms', ['user_id'], unique=False)
    op.add_column('leads', sa.Column('instagram_account_id', sa.UUID(), nullable=True))
    op.add_column('leads', sa.Column('placement', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_leads_ad_id'), 'leads', ['ad_id'], unique=False)
    op.create_index(op.f('ix_leads_adset_id'), 'leads', ['adset_id'], unique=False)
    op.create_index(op.f('ix_leads_form_id'), 'leads', ['form_id'], unique=False)
    op.create_index(op.f('ix_leads_instagram_account_id'), 'leads', ['instagram_account_id'], unique=False)
    op.create_index(op.f('ix_leads_page_id'), 'leads', ['page_id'], unique=False)
    op.create_foreign_key(None, 'leads', 'instagram_accounts', ['instagram_account_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_webhook_logs_user_id'), 'webhook_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_logs_user_id'), table_name='webhook_logs')
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_index(op.f('ix_leads_page_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_instagram_account_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_form_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_adset_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_ad_id'), table_name='leads')
    op.drop_column('leads', 'placement')
    op.drop_column('leads', 'instagram_account_id')
    op.drop_index(op.f('ix_forms_user_id'), table_name='forms')
    op.drop_index(op.f('ix_forms_page_id'), table_name='forms')
    op.drop_index(op.f('ix_facebook_pages_facebook_account_id'), table_name='facebook_pages')
    op.drop_index(op.f('ix_campaigns_ad_account_id'), table_name='campaigns')
    op.drop_column('campaigns', 'platform')
    op.drop_index(op.f('ix_adsets_user_id'), table_name='adsets')
    op.drop_index(op.f('ix_adsets_campaign_id'), table_name='adsets')
    op.drop_index(op.f('ix_ads_user_id'), table_name='ads')
    op.drop_index(op.f('ix_ads_adset_id'), table_name='ads')
    op.drop_index(op.f('ix_ad_accounts_facebook_account_id'), table_name='ad_accounts')
    op.drop_index(op.f('ix_instagram_accounts_user_id'), table_name='instagram_accounts')
    op.drop_index(op.f('ix_instagram_accounts_instagram_account_id'), table_name='instagram_accounts')
    op.drop_index(op.f('ix_instagram_accounts_id'), table_name='instagram_accounts')
    op.drop_index(op.f('ix_instagram_accounts_facebook_page_id'), table_name='instagram_accounts')
    op.drop_table('instagram_accounts')
    # ### end Alembic commands ###
